# application.yml
server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: anurag2002
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update   # 🔥 THIS LINE FIXES YOUR ISSUE
#    show-sql: true       # optional (good for debugging)
  shell:
    interactive:
      enabled: true
    history:
      enabled: true
  ai:
    google:
      genai:
        api-key: ${Api-key}
      chat:
        options:
          model: gemini-2.5-flash
  scaler:
    enabled: true
migration:
  path: ./migrations
  table: schema_history
  validate-on-migrate: true