# application.yml
server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: sigilotech
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update   # 🔥 THIS LINE FIXES YOUR ISSUE
#    show-sql: true       # optional (good for debugging)
  shell:
    interactive:
      enabled: true
    history:
      enabled: true
  ai:
    google:
      genai:
        api-key: AQ.Ab8RN6Kzn-vczuy2Jhul4rEQ4pmwQMbe9NJnF8sH7oO1ncBGfA
        chat:
          options:
            model: gemini-2.5-flash



migration:
  path: ./migrations
  table: schema_history
  validate-on-migrate: true